# Generated by Django 4.2.8 on 2023-12-06 14:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='access_code',
            field=models.CharField(default=blog.models.generate_random_access_code, max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='alignment',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='grid_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='winner',
            field=models.CharField(default='error', max_length=100),
        ),
    ]
