# Generated by Django 4.2.7 on 2023-12-16 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grid_size',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
