# Generated by Django 4.2.7 on 2023-12-16 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_grid_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alignment',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='grid_size',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
