# Generated by Django 4.2.7 on 2023-12-16 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_alignment_alter_post_grid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, size=None), default=list, size=None),
        ),
    ]
