# Generated by Django 4.2.7 on 2023-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_alignment_alter_post_grid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='played_positions',
            field=models.JSONField(default=list),
        ),
    ]
