# Generated by Django 4.2.7 on 2023-12-16 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, size=None), size=None),
        ),
    ]
