# Generated by Django 4.2.7 on 2023-12-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_played_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opponent',
            field=models.CharField(default='No opponent', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.CharField(default='No winner', max_length=100),
        ),
    ]
