# Generated by Django 4.2.7 on 2023-12-27 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='game',
        ),
        migrations.AddField(
            model_name='post',
            name='location_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
