# Generated by Django 4.2.7 on 2023-12-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_post_opponent_alter_post_author_alter_post_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='players',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.CharField(default='No winner', max_length=100),
        ),
    ]
