# Generated by Django 4.2.7 on 2023-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='players',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
