# Generated by Django 4.2.7 on 2023-12-31 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_post_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnerOfGame', to=settings.AUTH_USER_MODEL),
        ),
    ]
