# Generated by Django 4.2.7 on 2024-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_surrendered',
            field=models.BooleanField(default=False),
        ),
    ]
